/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

import se.chalmers.ait.dat215.lab2.*;

/**
 *
 * @author jonathan
 */
public class RecipeSearchRecipeModel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;
    
    private Recipe recipe;
    
    /**
     * Creates new customizer RecipeSearchRecipeModel
     */
    public RecipeSearchRecipeModel(Recipe recipe) {
        this.recipe = recipe;
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        infoPanel = new javax.swing.JPanel();
        portionsLabel = new javax.swing.JLabel();
        nbrOfPortionsLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        cuisineLabel = new javax.swing.JLabel();
        difficultyLabel = new javax.swing.JLabel();
        recipeTimeLabel = new javax.swing.JLabel();
        recipePriceLabel = new javax.swing.JLabel();
        recipeCouisineLabel = new javax.swing.JLabel();
        recipeDifficultyLabel = new javax.swing.JLabel();
        descriptionPane = new javax.swing.JScrollPane();
        descriptionTextPane = new javax.swing.JTextArea();
        ingredientsList = new javax.swing.JPanel();

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        nameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        nameLabel.setText(recipe.getName());

        infoPanel.setBackground(new java.awt.Color(200, 200, 200));

        portionsLabel.setText("Antal Portioner:");

        nbrOfPortionsLabel.setText(recipe.getServings() + "");

        timeLabel.setText("Tid:");

        priceLabel.setText("Pris:");

        cuisineLabel.setText("Kök:");

        difficultyLabel.setText("Svårighetsgrad:");

        recipeTimeLabel.setText(recipe.getTime() + " minuter");

        recipePriceLabel.setText(recipe.getPrice() + " kr");

        recipeCouisineLabel.setText(recipe.getCuisine());

        recipeDifficultyLabel.setText(recipe.getDifficulty());

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(portionsLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nbrOfPortionsLabel))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(difficultyLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recipeDifficultyLabel))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(timeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recipeTimeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recipePriceLabel))
                    .addGroup(infoPanelLayout.createSequentialGroup()
                        .addComponent(cuisineLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(recipeCouisineLabel)))
                .addContainerGap())
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(portionsLabel)
                    .addComponent(nbrOfPortionsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(timeLabel)
                    .addComponent(recipeTimeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLabel)
                    .addComponent(recipePriceLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuisineLabel)
                    .addComponent(recipeCouisineLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(difficultyLabel)
                    .addComponent(recipeDifficultyLabel))
                .addContainerGap(95, Short.MAX_VALUE))
        );

        descriptionTextPane.setColumns(20);
        descriptionTextPane.setRows(5);
        descriptionTextPane.setText(recipe.getDescription());
        descriptionPane.setViewportView(descriptionTextPane);

        javax.swing.GroupLayout ingredientsListLayout = new javax.swing.GroupLayout(ingredientsList);
        ingredientsList.setLayout(ingredientsListLayout);
        ingredientsListLayout.setHorizontalGroup(
            ingredientsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 217, Short.MAX_VALUE)
        );
        ingredientsListLayout.setVerticalGroup(
            ingredientsListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 284, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(descriptionPane, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ingredientsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addComponent(infoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descriptionPane)
                    .addComponent(ingredientsList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cuisineLabel;
    private javax.swing.JScrollPane descriptionPane;
    private javax.swing.JTextArea descriptionTextPane;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JPanel ingredientsList;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel nbrOfPortionsLabel;
    private javax.swing.JLabel portionsLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel recipeCouisineLabel;
    private javax.swing.JLabel recipeDifficultyLabel;
    private javax.swing.JLabel recipePriceLabel;
    private javax.swing.JLabel recipeTimeLabel;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
