/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

/**
 *
 * @author jonathan
 */
public class RecipeSearchSearchModel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer RecipeSearchSearchModel
     */
    public RecipeSearchSearchModel() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainIngredientRadioButton5 = new javax.swing.JRadioButton();
        mainIngredientRadioButton4 = new javax.swing.JRadioButton();
        mainIngredientRadioButton1 = new javax.swing.JRadioButton();
        mainIngredientRadioButton3 = new javax.swing.JRadioButton();
        mainIngredientRadioButton2 = new javax.swing.JRadioButton();
        countryRadioButton2 = new javax.swing.JRadioButton();
        timeLabel = new javax.swing.JLabel();
        countryRadioButton3 = new javax.swing.JRadioButton();
        difficultySlider = new javax.swing.JSlider();
        countryRadioButton1 = new javax.swing.JRadioButton();
        priceLabel = new javax.swing.JLabel();
        countryRadioButton6 = new javax.swing.JRadioButton();
        difficultyLabel = new javax.swing.JLabel();
        countryRadioButton4 = new javax.swing.JRadioButton();
        priceSlider = new javax.swing.JSlider();
        countryRadioButton5 = new javax.swing.JRadioButton();
        timeSlider = new javax.swing.JSlider();
        mainIngredientLabel = new javax.swing.JLabel();
        countryRadioButton7 = new javax.swing.JRadioButton();
        sourceCountryLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        priceTextField = new javax.swing.JFormattedTextField();
        timeTextField = new javax.swing.JFormattedTextField();

        mainIngredientRadioButton5.setText("Vegetariskt");

        mainIngredientRadioButton4.setText("Kyckling");

        mainIngredientRadioButton1.setSelected(true);
        mainIngredientRadioButton1.setText("Alla");
        mainIngredientRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientRadioButton1ActionPerformed(evt);
            }
        });

        mainIngredientRadioButton3.setText("Fisk");

        mainIngredientRadioButton2.setText("Kött");

        countryRadioButton2.setText("Sverige");

        timeLabel.setText("Tid");

        countryRadioButton3.setText("Grekland");

        difficultySlider.setMajorTickSpacing(50);
        difficultySlider.setPaintTicks(true);
        difficultySlider.setSnapToTicks(true);
        difficultySlider.setToolTipText("");
        difficultySlider.setValue(0);
        difficultySlider.setValueIsAdjusting(true);
        difficultySlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                difficultySliderStateChanged(evt);
            }
        });

        countryRadioButton1.setSelected(true);
        countryRadioButton1.setText("Alla");

        priceLabel.setText("Pris");

        countryRadioButton6.setText("Afrika");

        difficultyLabel.setText("Svårighetsgrad");

        countryRadioButton4.setText("Indien");

        priceSlider.setMajorTickSpacing(10);
        priceSlider.setMaximum(150);
        priceSlider.setMinorTickSpacing(10);
        priceSlider.setPaintTicks(true);
        priceSlider.setToolTipText("");
        priceSlider.setValue(0);
        priceSlider.setValueIsAdjusting(true);
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });

        countryRadioButton5.setText("Asien");

        timeSlider.setMajorTickSpacing(10);
        timeSlider.setMaximum(150);
        timeSlider.setMinorTickSpacing(10);
        timeSlider.setPaintTicks(true);
        timeSlider.setSnapToTicks(true);
        timeSlider.setToolTipText("");
        timeSlider.setValue(0);
        timeSlider.setValueIsAdjusting(true);
        timeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timeSliderStateChanged(evt);
            }
        });

        mainIngredientLabel.setText("Huvudingrediens");

        countryRadioButton7.setText("Frankrike");

        sourceCountryLabel.setText("Ursprungsland");

        searchButton.setText("Sök");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        priceTextField.setColumns(3);
        priceTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        priceTextField.setText("0");
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        timeTextField.setColumns(3);
        timeTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        timeTextField.setText("0");
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(priceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(difficultyLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(difficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(timeLabel)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceCountryLabel)
                            .addComponent(countryRadioButton3)
                            .addComponent(countryRadioButton2)
                            .addComponent(countryRadioButton4)
                            .addComponent(countryRadioButton5)
                            .addComponent(countryRadioButton1)
                            .addComponent(countryRadioButton6))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainIngredientLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mainIngredientRadioButton5)
                                        .addComponent(mainIngredientRadioButton4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mainIngredientRadioButton3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mainIngredientRadioButton2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(mainIngredientRadioButton1))))
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(countryRadioButton7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(searchButton))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(priceLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(difficultyLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultySlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sourceCountryLabel)
                            .addComponent(timeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryRadioButton1)
                            .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryRadioButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mainIngredientLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(mainIngredientRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainIngredientRadioButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainIngredientRadioButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainIngredientRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mainIngredientRadioButton5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(countryRadioButton7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(searchButton)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainIngredientRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainIngredientRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainIngredientRadioButton1ActionPerformed

    private void difficultySliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_difficultySliderStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_difficultySliderStateChanged

    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSliderStateChanged
       priceTextField.setText(priceSlider.getValue() + "");
    }//GEN-LAST:event_priceSliderStateChanged

    private void timeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timeSliderStateChanged
        timeTextField.setText(timeSlider.getValue() + "");
    }//GEN-LAST:event_timeSliderStateChanged

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchButtonActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_timeTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton countryRadioButton1;
    private javax.swing.JRadioButton countryRadioButton2;
    private javax.swing.JRadioButton countryRadioButton3;
    private javax.swing.JRadioButton countryRadioButton4;
    private javax.swing.JRadioButton countryRadioButton5;
    private javax.swing.JRadioButton countryRadioButton6;
    private javax.swing.JRadioButton countryRadioButton7;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JSlider difficultySlider;
    private javax.swing.JLabel mainIngredientLabel;
    private javax.swing.JRadioButton mainIngredientRadioButton1;
    private javax.swing.JRadioButton mainIngredientRadioButton2;
    private javax.swing.JRadioButton mainIngredientRadioButton3;
    private javax.swing.JRadioButton mainIngredientRadioButton4;
    private javax.swing.JRadioButton mainIngredientRadioButton5;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JFormattedTextField priceTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel sourceCountryLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JSlider timeSlider;
    private javax.swing.JFormattedTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
