/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package recipesearch;

import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JRadioButton;
import se.chalmers.ait.dat215.lab2.RecipeDatabase;
import se.chalmers.ait.dat215.lab2.SearchFilter;
import java.util.List;
import se.chalmers.ait.dat215.lab2.Recipe;

/**
 *
 * @author jonathan
 */
public class RecipeSearchSearchModel extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer RecipeSearchSearchModel
     */
    public RecipeSearchSearchModel(RecipeSearchView view) {
        initComponents();
        this.dataBase = RecipeDatabase.getSharedInstance();
        this.view = view;   
        
        
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cuisineButonGroup = new javax.swing.ButtonGroup();
        difficultyButtonGroup = new javax.swing.ButtonGroup();
        mainIngredientButtonGroup = new javax.swing.ButtonGroup();
        mainIngredientRadioButton5 = new javax.swing.JRadioButton();
        mainIngredientRadioButton4 = new javax.swing.JRadioButton();
        mainIngredientRadioButton1 = new javax.swing.JRadioButton();
        mainIngredientRadioButton3 = new javax.swing.JRadioButton();
        mainIngredientRadioButton2 = new javax.swing.JRadioButton();
        countryRadioButton2 = new javax.swing.JRadioButton();
        timeLabel = new javax.swing.JLabel();
        countryRadioButton3 = new javax.swing.JRadioButton();
        countryRadioButton1 = new javax.swing.JRadioButton();
        priceLabel = new javax.swing.JLabel();
        countryRadioButton6 = new javax.swing.JRadioButton();
        difficultyLabel = new javax.swing.JLabel();
        countryRadioButton4 = new javax.swing.JRadioButton();
        priceSlider = new javax.swing.JSlider();
        countryRadioButton5 = new javax.swing.JRadioButton();
        timeSlider = new javax.swing.JSlider();
        mainIngredientLabel = new javax.swing.JLabel();
        countryRadioButton7 = new javax.swing.JRadioButton();
        sourceCountryLabel = new javax.swing.JLabel();
        searchButton = new javax.swing.JButton();
        priceTextField = new javax.swing.JFormattedTextField();
        timeTextField = new javax.swing.JFormattedTextField();
        difficultyRadioButton1 = new javax.swing.JRadioButton();
        difficultyRadioButton2 = new javax.swing.JRadioButton();
        difficultyRadioButton3 = new javax.swing.JRadioButton();

        setPreferredSize(new java.awt.Dimension(541, 295));

        mainIngredientButtonGroup.add(mainIngredientRadioButton5);
        mainIngredientRadioButton5.setText("Vegetariskt");
        mainIngredientRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientChanged(evt);
            }
        });

        mainIngredientButtonGroup.add(mainIngredientRadioButton4);
        mainIngredientRadioButton4.setText("Kyckling");
        mainIngredientRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientChanged(evt);
            }
        });

        mainIngredientButtonGroup.add(mainIngredientRadioButton1);
        mainIngredientRadioButton1.setSelected(true);
        mainIngredientRadioButton1.setText("Alla");
        mainIngredientRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientChanged(evt);
            }
        });

        mainIngredientButtonGroup.add(mainIngredientRadioButton3);
        mainIngredientRadioButton3.setText("Fisk");
        mainIngredientRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientChanged(evt);
            }
        });

        mainIngredientButtonGroup.add(mainIngredientRadioButton2);
        mainIngredientRadioButton2.setText("Kött");
        mainIngredientRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainIngredientChanged(evt);
            }
        });

        cuisineButonGroup.add(countryRadioButton2);
        countryRadioButton2.setText("Sverige");
        countryRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        timeLabel.setText("Tid");

        cuisineButonGroup.add(countryRadioButton3);
        countryRadioButton3.setText("Grekland");
        countryRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        cuisineButonGroup.add(countryRadioButton1);
        countryRadioButton1.setSelected(true);
        countryRadioButton1.setText("Alla");
        countryRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        priceLabel.setText("Pris");

        cuisineButonGroup.add(countryRadioButton6);
        countryRadioButton6.setText("Afrika");
        countryRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        difficultyLabel.setText("Svårighetsgrad");

        cuisineButonGroup.add(countryRadioButton4);
        countryRadioButton4.setText("Indien");
        countryRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        priceSlider.setMajorTickSpacing(10);
        priceSlider.setMaximum(150);
        priceSlider.setMinorTickSpacing(10);
        priceSlider.setPaintTicks(true);
        priceSlider.setToolTipText("");
        priceSlider.setValue(0);
        priceSlider.setValueIsAdjusting(true);
        priceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                priceSliderStateChanged(evt);
            }
        });

        cuisineButonGroup.add(countryRadioButton5);
        countryRadioButton5.setText("Asien");
        countryRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        timeSlider.setMajorTickSpacing(10);
        timeSlider.setMaximum(150);
        timeSlider.setMinorTickSpacing(10);
        timeSlider.setPaintTicks(true);
        timeSlider.setSnapToTicks(true);
        timeSlider.setToolTipText("");
        timeSlider.setValue(0);
        timeSlider.setValueIsAdjusting(true);
        timeSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                timeSliderStateChanged(evt);
            }
        });

        mainIngredientLabel.setText("Huvudingrediens");

        cuisineButonGroup.add(countryRadioButton7);
        countryRadioButton7.setText("Frankrike");
        countryRadioButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuisineChanged(evt);
            }
        });

        sourceCountryLabel.setText("Ursprungsland");

        searchButton.setText("Sök");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        priceTextField.setColumns(3);
        priceTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        priceTextField.setText("0");
        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        timeTextField.setColumns(3);
        timeTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        timeTextField.setText("0");
        timeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timeTextFieldActionPerformed(evt);
            }
        });

        difficultyButtonGroup.add(difficultyRadioButton1);
        difficultyRadioButton1.setText("Lätt");
        difficultyRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyChanged(evt);
            }
        });

        difficultyButtonGroup.add(difficultyRadioButton2);
        difficultyRadioButton2.setText("Mellan");
        difficultyRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyChanged(evt);
            }
        });

        difficultyButtonGroup.add(difficultyRadioButton3);
        difficultyRadioButton3.setText("Svår");
        difficultyRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultyChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(priceLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(timeLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(difficultyLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(difficultyRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(difficultyRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(difficultyRadioButton3)))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sourceCountryLabel)
                            .addComponent(countryRadioButton3)
                            .addComponent(countryRadioButton2)
                            .addComponent(countryRadioButton4)
                            .addComponent(countryRadioButton5)
                            .addComponent(countryRadioButton1)
                            .addComponent(countryRadioButton6))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mainIngredientLabel)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(mainIngredientRadioButton5)
                                        .addComponent(mainIngredientRadioButton4, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mainIngredientRadioButton3, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(mainIngredientRadioButton2, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(mainIngredientRadioButton1)
                                    .addComponent(searchButton)))))
                    .addComponent(countryRadioButton7))
                .addGap(0, 9, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(timeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(priceLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(priceSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(sourceCountryLabel)
                                    .addComponent(timeLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(countryRadioButton1)
                                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countryRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countryRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countryRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(countryRadioButton5))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainIngredientLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(mainIngredientRadioButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainIngredientRadioButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainIngredientRadioButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainIngredientRadioButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(mainIngredientRadioButton5)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(countryRadioButton6)
                            .addComponent(difficultyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(difficultyRadioButton1)
                                .addComponent(difficultyRadioButton2)
                                .addComponent(difficultyRadioButton3))
                            .addComponent(countryRadioButton7)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(searchButton)))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void priceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_priceSliderStateChanged
       priceTextField.setText(priceSlider.getValue() + "");
       this.maxPrice = priceSlider.getValue();
    }//GEN-LAST:event_priceSliderStateChanged

    private void timeSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_timeSliderStateChanged
        timeTextField.setText(timeSlider.getValue() + "");
        this.maxTime = timeSlider.getValue();
    }//GEN-LAST:event_timeSliderStateChanged

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
     List<Recipe> result = RecipeDatabase.getSharedInstance().search(new SearchFilter(null, 60, null, 0, "Kött"));
     System.out.println(result.toString());
     RecipeSearchResultModel model = new RecipeSearchResultModel(result);
    }//GEN-LAST:event_searchButtonActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        try {
           this.priceSlider.setValue(Integer.parseInt(priceTextField.getText()));
        } catch(NumberFormatException e) {
            priceTextField.setText(Integer.toString(priceSlider.getValue()));
        }
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void timeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timeTextFieldActionPerformed
        try {
           this.timeSlider.setValue(Integer.parseInt(timeTextField.getText()));
        } catch(NumberFormatException e) {
            timeTextField.setText(Integer.toString(timeSlider.getValue()));
        }
    }//GEN-LAST:event_timeTextFieldActionPerformed

    private void cuisineChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuisineChanged
        JRadioButton temp =(JRadioButton)evt.getSource(); 
        this.cousine = temp.getText();
        disableRadioButtons(temp, cuisineButonGroup);
        
        
    }//GEN-LAST:event_cuisineChanged

    private void mainIngredientChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainIngredientChanged
        JRadioButton temp =(JRadioButton)evt.getSource(); 
        this.mainIngredient = temp.getText();
        disableRadioButtons(temp, mainIngredientButtonGroup);
    }//GEN-LAST:event_mainIngredientChanged

    private void difficultyChanged(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultyChanged
         JRadioButton temp =(JRadioButton)evt.getSource(); 
        this.difficulty = temp.getText();
        disableRadioButtons(temp, difficultyButtonGroup);
    }//GEN-LAST:event_difficultyChanged

    //method for disabling all other radiobuttons in a group
    //except the last one to be checked.
    
    private void disableRadioButtons(JRadioButton lastSelected, ButtonGroup btnGroup){
            btnGroup.clearSelection();
            lastSelected.setSelected(true);
        
           }
    
    
    //Variables for the values of the fields   
    private int maxTime;
    private int maxPrice;
    private String cousine;
    private String difficulty;
    private String mainIngredient;
    RecipeDatabase dataBase;
    RecipeSearchView view;
    
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton countryRadioButton1;
    private javax.swing.JRadioButton countryRadioButton2;
    private javax.swing.JRadioButton countryRadioButton3;
    private javax.swing.JRadioButton countryRadioButton4;
    private javax.swing.JRadioButton countryRadioButton5;
    private javax.swing.JRadioButton countryRadioButton6;
    private javax.swing.JRadioButton countryRadioButton7;
    private javax.swing.ButtonGroup cuisineButonGroup;
    private javax.swing.ButtonGroup difficultyButtonGroup;
    private javax.swing.JLabel difficultyLabel;
    private javax.swing.JRadioButton difficultyRadioButton1;
    private javax.swing.JRadioButton difficultyRadioButton2;
    private javax.swing.JRadioButton difficultyRadioButton3;
    private javax.swing.ButtonGroup mainIngredientButtonGroup;
    private javax.swing.JLabel mainIngredientLabel;
    private javax.swing.JRadioButton mainIngredientRadioButton1;
    private javax.swing.JRadioButton mainIngredientRadioButton2;
    private javax.swing.JRadioButton mainIngredientRadioButton3;
    private javax.swing.JRadioButton mainIngredientRadioButton4;
    private javax.swing.JRadioButton mainIngredientRadioButton5;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JSlider priceSlider;
    private javax.swing.JFormattedTextField priceTextField;
    private javax.swing.JButton searchButton;
    private javax.swing.JLabel sourceCountryLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JSlider timeSlider;
    private javax.swing.JFormattedTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
